#include <math.h>
#include <stdio.h>
#include <stdint.h>

#define smooth_kernel_size 3
#define sigma 0.707

//#define K 50

#define image_size 3

int main(){
    float gauss[smooth_kernel_size][smooth_kernel_size];
    float gauss2[smooth_kernel_size][smooth_kernel_size];


    float img[image_size][image_size]={
        {30, 65, 138},
        {53,230, 240},
        {59, 87, 14}
    };
    /*
    float img[image_size][image_size]={
        {30, 65, 138, 26},
        {53,230, 240, 245},
        {59, 87, 14, 99},
        {112, 10, 90, 196}
    };
    */

    float img2[image_size][image_size] = {};
    //float img2[image_size+2][image_size+2] = {};

    float img3[image_size][image_size] = {};

    float sum = 0;
    int i, j;

    for (i = 0; i < smooth_kernel_size; i++) {
        for (j = 0; j < smooth_kernel_size; j++) {
            float x = i - (smooth_kernel_size - 1) / 2.0;
            float y = j - (smooth_kernel_size - 1) / 2.0;
            gauss[i][j] = 0.16*(1/sigma) * exp(((pow(x, 2) + pow(y, 2)) / ((2 * pow(sigma, 2)))) * (-1));
            sum += gauss[i][j];
        }
    }

    printf("The Filter Generated by Testcase\n ");
    for (i = 0; i < smooth_kernel_size; i++) {
        for (j = 0; j < smooth_kernel_size; j++) {
            gauss[i][j] /= sum;
            printf("%f ", gauss[i][j]);
        }
         printf("\n");
    }

    printf("\nThe Filter FP32\n");
    for (i = 0; i < smooth_kernel_size; i++) {
        for (j = 0; j < smooth_kernel_size; j++) {
            printf("%a ", gauss[i][j]);
            printf("\t");
        }
        printf("\n");
    }

    return 0;
}
